Repository test-fullautomation/robotframework-documentation, pull requests merged in 2024-05, with the labels that each got.

#60 add python-testresultdbaccess repo
  maindoc/maindoc_configs/maindoc_config_OSS.json
Labels: enhancement, 0.12.0

#61 update date for config file and add release info
  config/robotframework_aio/release_items_RobotFrameworkAIO_Documentation.json
  maindoc/maindoc_configs/maindoc_config_OSS.json
Labels: 0.12.0

#66 Added PrometheusInterface to configuration of main documentation
  maindoc/maindoc_configs/maindoc_config_OSS.json
Labels: documentation, 0.12.1
